#!/usr/bin/env node
// Fetches real road distances for every travel leg and caches them next to the
// trip file.
//
//   npm run routes                      the only trip
//   npm run routes -- trips/x.json
//   npm run routes -- --force           refetch legs already cached
//
// Deliberately built on the COMMITTED coordinates, never the private overlay,
// so the cache it writes is safe to commit.
//
// The public OSRM server hosts only the car profile. It answers "walking" and
// "cycling" requests with car routing, so its durations are meaningless for
// anything but driving. What is genuine is the road distance, which is what we
// keep; per-mode times are derived from it in src/lib/modes.mjs.
import { writeFileSync, existsSync, readFileSync } from 'node:fs';
import { loadTrip, legKey } from '../src/lib/load.mjs';

const ROOT = new URL('../', import.meta.url);
const argv = process.argv.slice(2);
const force = argv.includes('--force');
// --private routes from the overlay's real coordinates into a gitignored cache.
// Public coordinates are rounded to about a kilometre, which turns a ten minute
// walk from your door into a forty minute one, so local accuracy needs its own
// pass.
const priv = argv.includes('--private');
const tripArg = argv.find((a) => !a.startsWith('--'));

const { slug, trip, byId, errors, legs } = loadTrip(tripArg, { applyOverlay: priv });
if (errors.length) {
  for (const e of errors) console.error(`ERROR ${e}`);
  console.error('\nFix the trip file first. Nothing fetched.');
  process.exit(1);
}

const outPath = priv
  ? new URL(`resources/${slug}.routes.json`, ROOT)
  : new URL(`trips/${slug}.routes.json`, ROOT);
const cache = existsSync(outPath) && !force
  ? JSON.parse(readFileSync(outPath, 'utf8'))
  : { _readme: priv
      ? 'Generated by `npm run routes -- --private`. Derived from real coordinates in resources/private.json. GITIGNORED, never commit.'
      : 'Generated by `npm run routes`. Road distances from OSRM, derived from the committed coordinates. Safe to commit.',
      legs: {} };
cache.legs ??= {};

const pairs = new Map();
for (const l of legs) pairs.set(legKey(l.fromId, l.toId), [l.fromId, l.toId]);

const todo = [...pairs.entries()].filter(([k]) => force || !cache.legs[k]);
console.log(`${pairs.size} distinct legs, ${todo.length} to fetch\n`);

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
let ok = 0, failed = 0;

for (const [key, [fromId, toId]] of todo) {
  const a = byId.get(fromId), b = byId.get(toId);
  const url = `https://router.project-osrm.org/route/v1/driving/` +
    `${a.lon},${a.lat};${b.lon},${b.lat}?overview=false`;
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(15000) });
    const json = await res.json();
    if (json.code !== 'Ok' || !json.routes?.length) throw new Error(json.code || 'no route');
    const r = json.routes[0];
    cache.legs[key] = {
      roadKm: Math.round((r.distance / 1000) * 100) / 100,
      carMin: Math.round((r.duration / 60) * 10) / 10,
    };
    ok++;
    console.log(`  ok   ${a.name} -> ${b.name}  ${cache.legs[key].roadKm} km`);
  } catch (e) {
    failed++;
    console.warn(`  fail ${a.name} -> ${b.name}  (${e.message}); will fall back to an estimate`);
  }
  await sleep(220); // the demo server is a shared courtesy, not a product
}

writeFileSync(outPath, JSON.stringify(cache, null, 2) + '\n');
const where = priv ? `resources/${slug}.routes.json (gitignored)` : `trips/${slug}.routes.json`;
console.log(`\n${ok} fetched, ${failed} failed, ${Object.keys(cache.legs).length} cached in ${where}`);
if (failed) console.log('Failed legs fall back to straight-line distance with a detour factor, and are marked as estimates in the UI.');
